# Generated by Django 4.0.4 on 2022-04-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_todocreator_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='abc',
        ),
    ]
