# Generated by Django 4.0.4 on 2022-04-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_user_todo_abc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='abc',
            new_name='todocreator',
        ),
    ]
