# Generated by Django 4.0.4 on 2022-04-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_abc_todo_todocreator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='url',
        ),
    ]
